// Code generated by MockGen. DO NOT EDIT.
// Source: uuid.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockIUUID is a mock of IUUID interface.
type MockIUUID struct {
	ctrl     *gomock.Controller
	recorder *MockIUUIDMockRecorder
}

// MockIUUIDMockRecorder is the mock recorder for MockIUUID.
type MockIUUIDMockRecorder struct {
	mock *MockIUUID
}

// NewMockIUUID creates a new mock instance.
func NewMockIUUID(ctrl *gomock.Controller) *MockIUUID {
	mock := &MockIUUID{ctrl: ctrl}
	mock.recorder = &MockIUUIDMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUUID) EXPECT() *MockIUUIDMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockIUUID) New() uuid.UUID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockIUUIDMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockIUUID)(nil).New))
}
